### DISCUSSION TITLE
Change between http/https using env vars?

### DISCUSSION THREAD

**Discussion by amr** [dropwizard/dropwizard#4768] [General]
Most probably like everyone else, my DW configuration uses env vars substitution. This works 90% of the time but fails to work when changing a config value requires adding or removing other config properties, like in our app connectors:

I've tried the following, in hopes of supporting both `http` and `https`:
```
  applicationConnectors:
    - type: ${APP_HTTP_CONNECTOR:-http}
      port: ${APP_HTTP_PORT:-8080}
      keyStorePath: ${APP_HTTP_KEY_STORE_PATH:-null}
      keyStorePassword: ${APP_HTTP_KEY_STORE_PASSWORD:-null}
      keyStoreType: ${APP_HTTP_KEY_STORE_TYPE:-null}
```

Which works for `https` when I provide the env vars above. The problem is, as soon as the `type` field is `http`, I get a config validation error:
```
  * Unrecognized field at: server.applicationConnectors.[0].keyStorePath
    Did you mean?:
      - port
      - bindHost
      - idleTimeout
      - useDateHeader
      - selectorThreads
        [20 more]
```

Because it's trying to set `keyStorePath` field on the `HttpConnectorFactory`.

1. Is this doable in some other way that I missed?
2. If not, do you agree that it's reasonable to support that functionality? If yes, we could start discussing possible simple approaches to supporting that kind of thing.

**Comment by amr** [comment]
Possibly related: #3442

**Comment by joschi** [comment]
The problem is that you're trying to assign a configuration setting (`keyStorePath`) which doesn't exist in [`HttpConnectorFactory`](https://github.com/dropwizard/dropwizard/blob/v2.0.13/dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java) but only in [`HttpsConnectorFactory`](https://github.com/dropwizard/dropwizard/blob/v2.0.13/dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpsConnectorFactory.java#L230-L234) and the `type` field determines which of the factories to use.

So once `type: http` has been evaluated, Dropwizard (Jackson) will try to deserialize that part into an `HttpConnectorFactory` instance.

**Comment by amr** [comment]
@joschi Exactly, that's my understanding too. Do you think there is some other way to achieve the end result? That is, be able to switch between http/https using env vars?

Yesterday I experimented with an approach using YAML anchors. Basically:
```
x-http-connector: &http-connector
  - type: http
    port: ${APP_HTTP_PORT:-8080}

x-https-connector: &https-connector
  - type: https
    port: ${APP_HTTP_PORT:-443}
    keyStorePath: ${APP_HTTP_KEY_STORE_PATH:-null}
    keyStorePassword: ${APP_HTTP_KEY_STORE_PASSWORD:-null}
    keyStoreType: ${APP_HTTP_KEY_STORE_TYPE:-null}

server:
  type: default
  registerDefaultExceptionMappers: false
  applicationContextPath: /api
  applicationConnectors: *${APP_HTTP_CONNECTOR:-http}-connector
```

I also annotated my `Configuration` class with `@JsonIgnoreProperties({"x-https-connector", "x-http-connector"})` to get DW config validation to ignore these 2.

I couldn't get this to work yet, because Jackson didn't understand the YAML anchor reference, which I believe it supports --  perhaps I just need to toggle some object mapper options or apply some annotations somewhere.

I wonder if there are other approaches to that problem though.

**Comment by mattnelson** [comment]
> I wonder if there are other approaches to that problem though.

Use an environment variable to flex which config file is used.
```sh
set CONFIG_FILE=http_config.yaml
java -jar server.jar server $CONFIG_FILE
# or
set CONFIG_FILE=https_config.yaml
java -jar server.jar server $CONFIG_FILE
```

Another option is to have multiple application connectors active at the same time.
```yaml
  applicationConnectors:
  - type: http
    port: 8080
  - type: https
    port: 8443
    keyStorePath: ...
```
