### DISCUSSION TITLE
Dropwizard Server Configuratiuons

### DISCUSSION THREAD

**Discussion by umar18** [dropwizard/dropwizard#5556] [General]
I have successfully deployed my application on my local server. The problem is that i can access the server using localhost/ip on the server but unable to access it using the server IP locally or from other machine on the same network. And "Yes", my network is configured correctly. Can someone help please. Here is my server configurations:

```yaml
server:
  application_connectors:
  - type: http
    port: 8989
  request_log:
      appenders: []
  admin_connectors:
  - type: http
    port: 8991
```
