### DISCUSSION TITLE
Cannot disable default console logging

### DISCUSSION THREAD

**Discussion by kkolyan** [dropwizard/dropwizard#7156] [Q&A] [answered]
Hi. I'm using cassandra-reaper, which is powered by dropwizard. 
I'm trying to configure it to NOT log anything to console, because console forwarded to journalctl, where it's completely redundant (it's enough to see bash message like "Starting java process...").
Tried following configuration:
```
logging:
  level: INFO
  loggers:
    io.dropwizard: WARN
    org.eclipse.jetty: WARN
  appenders:
    - type: file
      logFormat: "AZAZA %d [%thread] %-5level - [%X] %logger{36} - %msg%n"
      currentLogFilename: /var/log/cassandra-reaper/reaper.log
      archivedLogFilenamePattern: /var/log/cassandra-reaper/reaper-%d.log.gz
      archivedFileCount: 99
```
But it logs to console using magical defaults. I've also tried to set treshold by following:
```
logging:
  level: INFO
  loggers:
    io.dropwizard: WARN
    org.eclipse.jetty: WARN
  appenders:
    - type: console
      logFormat: "dsadsda %d [%thread] %-5level - [%X] %logger{36} - %msg%n"
      threshold: OFF
    - type: file
      logFormat: "AZAZA %d [%thread] %-5level - [%X] %logger{36} - %msg%n"
      currentLogFilename: /var/log/cassandra-reaper/reaper.log
      archivedLogFilenamePattern: /var/log/cassandra-reaper/reaper-%d.log.gz
      archivedFileCount: 99
```
and also, after examining code tried to replace OFF with false, tried to replace it with NONE, tried to surround it with quotes - but still, if I try to somehow disable it, its magically recovers.

Dropwizard version: 2.0.34
