### DISCUSSION TITLE
Looking for examples of mTLS using dropwizard

### DISCUSSION THREAD

**Discussion by harpreet86** [dropwizard/dropwizard#8512] [Q&A]
I want my dropwizard application to be mTLS enabled for which I am not able to find some examples or reference.
Also, if someone can help how to test this locally using some test certificates.

**Comment by joschi** [comment]
@harpreet86 Is there anything specific you're looking for?

mTLS in general just means that both, the client and the server, need to present their certificates to each other.

In Dropwizard, you can configure the HTTPS connector to require the clients to present a certificate:
https://www.dropwizard.io/en/stable/manual/configuration.html#https
```yaml
server:
  applicationConnectors:
    - type: https
      port: 8443
      ....
      needClientAuth: true
      wantClientAuth: true
```
These settings configure Jetty pretty much the same way as this example (without Dropwizard):
https://github.com/lawrenceching/jetty-mtls-example/blob/87c560c85c911605870ba0c318ebdb5164917b06/src/main/java/me/imlc/JettyMtlsServer.java

The client can be configured accordingly:
https://www.dropwizard.io/en/stable/manual/configuration.html#tls

**Comment by harpreet86** [comment]
Hi @joschi 

I have tried using below server configuration:
```
server:
  applicationConnectors:
    - type: https
      port: 8443
      keyStorePath: server-keystore.jks
      keyStorePassword: server-keystore-password
      keyManagerPassword: server-keymanager-password
      trustStorePath: server-truststore.jks
      trustStorePassword: server-trustStore-password
      needClientAuth: true
```

and the client class **main**  method has code as below:
```
SslConfigurator sslConfigurator = SslConfigurator.newInstance();
        //Register a keystore
        sslConfigurator
            .keyStoreFile("client-keystore.jks")
            .keyPassword("client-keystore-password")
            .trustStoreFile("client-truststore.jks")
            .trustStorePassword("client-truststore-password");
        //Create SSL Context
        SSLContext sSLContext = sslConfigurator.createSSLContext();
        //Obtain client
        Client client = ClientBuilder
            .newBuilder()
            .sslContext(sSLContext)
            .build();

        try {
            WebTarget target = client.target("https://localhost:8443/user");
            Response response = target.request().get();
            System.out.println(response);
            System.out.println(response.getEntity());
            // Handle the response as needed

        } finally {
            client.close();
        }
```

The above does not work as it gives bad certificate exception however the same example works if I change **needClientAuthentication** to **false**. I am not sure about what I am missing as I am not able to find any good example to test these things on local machine.

Please suggest.
