### ISSUE TITLE
Specifying maxThreads per application

### ISSUE THREAD

**Issue by ajermakovics** [dropwizard/dropwizard#1477]
Hi all

Ran into this one issue when trying to specify maxThreads. With this config:

``` yml
server:
  applicationConnectors:
    - type: http
      port: 8080
      acceptorThreads: 4
      selectorThreads: 8
  adminConnectors:
    - type: http
      port: 8081
      acceptorThreads: 4
      selectorThreads: 8
  maxThreads: 20
```

the server won't start due to an exception:

```
java.lang.IllegalStateException: Insufficient threads: max=20 < needed(acceptors=8 + selectors=16 + request=1)
    at org.eclipse.jetty.server.Server.doStart(Server.java:350)
```

Looking at the source `maxThreads` only applies to the `applicationConnectors` and the `InstrumentedQueuedThreadPool` that they use (`AbstractServerFactory::createThreadPool`). Admin connectors have their own QueuedThreadPool and `maxThreads` doesn't apply to it.

Seems like `maxThreads: 20` should have been enough: 4 acceptor + 8 selector + 8 request threads. Should it not?

Using Dropwizard 0.9.2.
Thanks!

**Comment by thomaslee** [comment]
> Looking at the source maxThreads only applies to the applicationConnectors and the InstrumentedQueuedThreadPool that they use (AbstractServerFactory::createThreadPool). Admin connectors have their own QueuedThreadPool and maxThreads doesn't apply to it.

Perhaps the code has changed since you looked at it, but to me it looks to me like:

1. Application connectors and admin connectors are added to a common Jetty `Server` instance.
1. That `Server` instance itself has a single thread pool of up to `maxThreads` threads.

What seems to be happening here is the total number of threads configured for your application connectors + admin connectors exceeds the maximum number of threads in the (shared) thread pool.

Relevant code: https://github.com/dropwizard/dropwizard/blob/d6dfbcbf821fd1b7f3aab881c34302095f3a3cfc/dropwizard-core/src/main/java/io/dropwizard/server/DefaultServerFactory.java#L159-L173

As such this *seems* to be expected behavior. Would you agree?

**Comment by ajermakovics** [comment]
Hey @thomaslee 

Yes, looks like that is the place where application thread pool is created: [DefaultServerFactory.java#L159-L173](https://github.com/dropwizard/dropwizard/blob/d6dfbcbf821fd1b7f3aab881c34302095f3a3cfc/dropwizard-core/src/main/java/io/dropwizard/server/DefaultServerFactory.java#L159-L173)

And then there is the Admin threadpool created here [DefaultServerFactory.java#L218](https://github.com/dropwizard/dropwizard/blob/d6dfbcbf821fd1b7f3aab881c34302095f3a3cfc/dropwizard-core/src/main/java/io/dropwizard/server/DefaultServerFactory.java#L218)

The app threadpool uses the `maxThreads` setting and admin uses `adminMaxThreads`. I've just tried to start an app using 1.0.0-rc2 and this config: 
```yml
server:
  maxThreads: 20
  adminMaxThreads: 20
  applicationConnectors:
    - type: http
      port: 8080
      acceptorThreads: 4
      selectorThreads: 8
  adminConnectors:
    - type: http
      port: 8081
      acceptorThreads: 4
      selectorThreads: 8
```
but the result was the same. 

Tbh, I would have expected the app to start with these settings. It appears like there's a mismatch between the config and Jetty's threadpool validation.

In here [Server.java#L356-L374] (https://github.com/eclipse/jetty.project/blob/c99c02e2f59cc4c65cc9b893710e48eeeb3bef0b/jetty-server/src/main/java/org/eclipse/jetty/server/Server.java#L356-L374) Jetty sums up application and admin connectors. And then compares the sum to **only** the application threadpool. Not quite sure what's the best way to solve it though.
