### ISSUE TITLE
new logback versions do not log to file 

### ISSUE THREAD

**Issue by chas678** [dropwizard/dropwizard#1478]
Dropwizard 0.9.2 uses Logback 1.1.3.  Attempting to use newer versions of Logback 1.1.5 + 1.1.6 mean that logs are longer written to file when configured to do so in the YAML which violates the principle of least astonishment.

## Steps to reproduce

1. change pom to use logback version 1.1.5 or 1.1.6
1. Run a service locally with a file appender configured in the YAML - for example: 

```yaml
logging:
  level: INFO
  loggers:
    "com.example": DEBUG
  appenders:
    - type: console
      target: stdout
      timeZone: UTC
      logFormat: "%-5p [%d{ISO8601,UTC}] %7X{userUUID} %c: %m%n%rEx"
    - type: file
      threshold: ALL
      currentLogFilename: /tmp/example-service/server.log
      archivedLogFilenamePattern: /tmp/app/example-service/server-%d.log.gz
      archivedFileCount: 20
      timeZone: UTC
      logFormat: "%-5p [%d{ISO8601,UTC}] %7X{userUUID} %c: %m%n%rEx"
```
## Expected results
* Log goes to console and also to file at ` /tmp/example-service/server.log`

## Actual results
* log goes to console, but no file is created in ` /tmp/example-service/server.log`

## Suspicion/Guess as to cause
Logback has changed the way MDC is inherited by threads .

## Refs
* Logback release notes : http://logback.qos.ch/news.html
