### ISSUE TITLE
liquibase db dump not working

### ISSUE THREAD

**Issue by devinrsmith** [dropwizard/dropwizard#1497]
https://dropwizard.github.io/dropwizard/0.9.2/docs/manual/migrations.html

suggests that `java -jar hello-world.jar db dump helloworld.yml` will generate a liquibase schema. I've definitely got a non-empty db, configured like:

```
  database:
    driverClass: org.h2.Driver
    user: username
    password: super_secret
    url: jdbc:h2:./target/mydb
```

I've added the correct bundle, and the command executes but outputs an empty xml tree:

```
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd"/>
```
