### ISSUE TITLE
File not logging at INFO

### ISSUE THREAD

**Issue by dehora** [dropwizard/dropwizard#154]
I might be doing something stupid here, if so, apologies, but I have this logging configured

```
logging:
  level: DEBUG
  loggers:
    "net.amadan.sal.migration.MigrationResource": DEBUG
  console:
    enabled: true
    threshold: INFO
  file:
    enabled: true
    threshold: INFO
    currentLogFilename: migration.log
    archivedLogFilenamePattern: migration-%d.log.gz
    archivedFileCount: 50
    timeZone: UTC
```

and with that, nothing gets written to the log file. If I change file/threshold to DEBUG/ALL, I see file logging. Is that intentional?
