### ISSUE TITLE
* Unrecognized field at: logging.type

### ISSUE THREAD

**Issue by Madhukar07565** [dropwizard/dropwizard#1598]
```
logging:
  level: INFO
  loggers:
    "io.dropwizard": INFO
    "org.hibernate.SQL":
      level: DEBUG
      additive: false
      appenders:
        - type: file
          currentLogFilename: /var/log/myapplication-sql.log
          archivedLogFilenamePattern: /var/log/myapplication-sql-%d.log.gz
          archivedFileCount: 5
  appenders:
    - type: console
```
When i have added the above configuration in yaml file i am getting the below error.
```
* Unrecognized field at: logging.type
    Did you mean?:
      - level
      - loggers
      - appenders
```
