### ISSUE TITLE
Providing a logFormat on requestLog appenders results in PARSER_ERROR

### ISSUE THREAD

**Issue by tjcutajar** [dropwizard/dropwizard#1659]
Example

```
  requestLog:
    appenders:
      - type: console
        logFormat: "%-5level [%thread]: %message%n"
```

produces this in logs

> %PARSER_ERROR[level] [%PARSER_ERROR[thread]]: %PARSER_ERROR[message]

DW 1.0
