### ISSUE TITLE
Size based rollover logging broken in 1.0.0

### ISSUE THREAD

**Issue by oddmar** [dropwizard/dropwizard#1691]
We use size based rollover logging in DW. After upgrading to 1.0.0, no log files are produced at all. I have recreated the problem with a completely basic app (pretty much from the Getting Started example). 

The following configuration file will result in NO logging whatsoever:
```
server:
  type: simple
  connector:
    type: http
    port: 9090

logging:
  level: TRACE
  appenders:
    - type: file
      currentLogFilename: ./logs/example.log
      archivedLogFilenamePattern: ./logs/example.%i.log.gz
      archivedFileCount: 5
      maxFileSize: 1KB
```

I have found that changing the archivedLogFilenamePattern to the following will cause logging to work again: `archivedLogFilenamePattern: ./logs/example.%d.%i.log.gz`

So adding a size and time based rolling policy works, but it is not exactly what we wanted. A purely time based rolling policy also works fine.

I attempted to recreate the problem with logback only, but was not able to. So I suspect the problem lies in io.dropwizard.logging.FileAppenderFactory.buildAppender.
