### ISSUE TITLE
server.connector is not parsed

### ISSUE THREAD

**Issue by BethyDiakabananas** [dropwizard/dropwizard#1703]
Hi all, 

I'm trying to deploy an app on Heroku using Dropwizard and Gradle. Below is my `yaml` file:
```yaml
server:
  type: simple
  connector:
    type: http
    port: 8080
database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver
  # the username
  user: process.env.JDBC_DATABASE_USERNAME
  # the password
  password: process.env.JDBC_DATABASE_PASSWORD
  # the JDBC URL
  url: process.env.JDBC_DATABASE_URL
  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* Test Database Health Check */ SELECT 1"
  # the minimum number of connections to keep open
  minSize: 8
  # the maximum number of connections to keep open
  maxSize: 32
  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false
  # how long a connection must be held before it can be validated
  evictionInterval: 10s
  # the maximum lifetime of an idle connection
  minIdleTime: 1 minute      
logging:
  level: INFO
```

Here's the `procfile` that would invoke this:

```procfile
web: java $JAVA_OPTS -Ddw.server.connector.type=http -Ddw.server.connector.port=$PORT -Ddw.database.user=$JDBC_DATABASE_USERNAME -Ddw.database.password=$JDBC_DATABASE_PASSWORD -Ddw.database.url=$JDBC_DATABASE_URL -jar build/libs/project-1.0.jar server config.yaml
```

Unfortunately the files cause this error when trying to deploy the app:

```
2016-08-22T02:50:46.914027+00:00 app[web.1]:   * Unrecognized field at: server.connector
2016-08-22T02:50:46.914033+00:00 app[web.1]: 
2016-08-22T02:50:47.011379+00:00 heroku[web.1]: Process exited with status 1
2016-08-22T02:50:47.024697+00:00 heroku[web.1]: State changed from starting to crashed
```

Is there anything I should change in the `yaml` file, or the `procfile`? Thank you in advance for your help
