### ISSUE TITLE
EDIT: Should requestLog be separate?

### ISSUE THREAD

**Issue by deeTEEcee** [dropwizard/dropwizard#1731]
This is the configuration for my dropwizard server using version 1.0.0.

```
server:
    requestLog:
        appenders:
        - type: file
          currentLogFilename: /logs/application.log
          archive: false
          # lowest level of eventrs to write to file
          threshold: ALL
          timeZone: UTC
          logFormat: # TODO
logging:
    level: INFO
    appenders:
    - type: file
      currentLogFilename: /logs/application.log
      archive: false
      # lowest level of eventrs to write to file
      threshold: ALL
      timeZone: UTC
      logFormat: # TODO
```

Unfortunately, only the ones in logging block show up. requestLog does not pipe to the same file like I want it to. Is there a way to do this?

On a side note, I can't seem to use yaml anchors either (to prevent duplication of these 2 equal file appenders)
