### ISSUE TITLE
No request logs in dropwizard 1.0.1

### ISSUE THREAD

**Issue by m-at-nu** [dropwizard/dropwizard#1737]
Hello,
since I've updated dropwizard to version 1.0.1 I have no request logs anymore, using dropwizard version 1.0.0 everything works. Is this a known bug or was anything changed regarding the configuration? According to the [release logs](https://github.com/dropwizard/dropwizard/blob/master/docs/source/about/release-notes.rst#v101-sep-21-2016), issue #1678 may be related to this? Even so, having only the requestLog's appenders without logging appenders doesn't work either with version 1.0.1.

I've attached my server configuration _server.yml_ file below:
```
server:
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8080
  requestLog:
    appenders:
      - type: console
logging:
  appenders:
    - type: console
````
I've also attached a small minimal working example. Please change the dropwizard version to 1.0.0 and 1.0.1 respectively to test the issue.

Thanks in advance!
[test.zip](https://github.com/dropwizard/dropwizard/files/489626/test.zip)
