### ISSUE TITLE
Size based rollover logging still broken in 1.0.2

### ISSUE THREAD

**Issue by looppair** [dropwizard/dropwizard#1789]
It looks `maxFileSize` handling was not fixed in #1691. Since upgrading past 0.9.3 the following configuration results in no request log at all:

```
server:
  type: default
  applicationConnectors:
    - type: http
      port: 80
  adminConnectors:
    - type: http
      port: 8081
  registerDefaultExceptionMappers: false
  requestLog:
    appenders:
      - type: console
      - type: file
        currentLogFilename: /var/log/service_name/request.log
        archivedLogFilenamePattern: /var/log/service_name/request.log.%i
        maxFileSize: 50MB
```

The following configuration results in a working request log at `/var/log/service_name/request.log`:

```
server:
  type: default
  applicationConnectors:
    - type: http
      port: 80
  adminConnectors:
    - type: http
      port: 8081
  registerDefaultExceptionMappers: false
  requestLog:
    appenders:
      - type: console
      - type: file
        currentLogFilename: /var/log/service_name/request.log
        archivedLogFilenamePattern: /var/log/service_name/request.log.%d
```

I tested these using 1.0.2, and can confirm that the full configuration (only slightly more complex) works in 0.9.2 and 0.9.3, and fails in 1.0.0, 1.0.1 and 1.0.2.

Size based log rotation is important for my project because we're working with limited disk space.
