### ISSUE TITLE
Request logging through syslog broken in DW1.0?

### ISSUE THREAD

**Issue by wilbertpol** [dropwizard/dropwizard#1801]
We have been using the following snippet to log requests through syslog:
```
# Listeners
server:
  applicationConnectors:
    - type: http
      port: 6720
  adminConnectors:
    - type: http
      port: 6721
  requestLog:
    appenders:
      - type: syslog
        threshold: ALL
        logFormat: "app-ms %msg"
```

This was still working fine in DW0.9.2. After upgrading to DW1.0.2 the requests are no longer getting logged through syslog; the regular application logging through syslog is still working fine.

Do we have to make some configuration changes?

**Comment by arteam** [comment]
Hi, @wilbertpol,

Thanks for reporting this issue. We migrated request logging in 1.0 from a native Jetty solution to `logback-access`. Unfortunately, it doesn't support syslog appenders, see [LOGBACK-317](http://jira.qos.ch/browse/LOGBACK-317). 

I think it can be considered a regression for Dropwizard, and we need to figure out a way to workaround this limitaion.

**Comment by mattnelson** [comment]
The logs could be configured to the console appender, then you can update your process command to redirect console to syslog.

**Comment by arteam** [comment]
Hi @wilbertpol,

Could you please try to update to Dropwizard 1.0.4? We brought back old-style request logging with `logback-classic` and it should work with the syslog appender. You need explicitly set the type of request logging factory, though:
```yaml
  requestLog:
    type: classic
    appenders:
      - type: syslog
        threshold: ALL
        logFormat: "app-ms %msg"
```
