### ISSUE TITLE
requestLog 'file' appender does not seem to work in 1.1.0

### ISSUE THREAD

**Issue by moxie0** [dropwizard/dropwizard#2042]
With or without "classic," these configurations create the specified request log file, but produce no output:

`````
server:
  requestLog:
    appenders:
      - type: console
      - type: file
        threshold: ALL
        logFormat: "%h %l %u [%t] \"%r\" %s %b \"%i{Referer}\" \"%i{User-Agent}\""
        currentLogFilename: test-requests.log
        archive: false
`````
or

`````
server:
  requestLog:
    type: classic
    appenders:
      - type: console
      - type: file
        threshold: ALL
        logFormat: null
        currentLogFilename: test-requests.log
        archive: false
`````
Prints to the console just fine, but not the file. I've tested with/without the console appender, with/without archiving, with/without specifying a `logFormat`, with/without `timeZone`. I never get any output.

**Comment by nickbabcock** [comment]
Hmm, I wasn't able to reproduce that behavior for v1.1.0 tag in the dropwizard-e2e module (where we do our end to end testings). I had the `App1Test` use the minimal config:

```yaml
server:
  applicationConnectors:
    - type: http
      port: 0
  adminConnectors:
    - type: http
      port: 0
  requestLog:
    appenders:
      - type: console
      - type: file
        threshold: ALL
        logFormat: "%h %l %u [%t] \"%r\" %s %b \"%i{Referer}\" \"%i{User-Agent}\""
        currentLogFilename: test-requests.log
        archive: false
```
And all requested endpoints were logged:

> 127.0.0.1 - - [02/May/2017:19:02:23 -0400] "GET /empty-optional HTTP/1.1" 204 0 "-" "App1 (test client 1)"

Is it possible to make a small reproducible case or provide more information?
