### ISSUE TITLE
requestContent and responseContent always return "-" in request log

### ISSUE THREAD

**Issue by Wstunes** [dropwizard/dropwizard#2045]
the request log config in my config.yaml is like the following
```
 requestLog:
    appenders:
      - type: file
        currentLogFilename: ./logs/runtimeService-requests.log
        archive: true
        archivedLogFilenamePattern: "./logs/runtimeService-requests-%i.log.gz"
        logFormat: "%h|%t{yyyy/MM/dd HH:mm:ss}|%D|%i{requestContent}|%i{responseContent}"
        maxFileSize: 5M
        archivedFileCount: 10
```

But  output of the requestContent and responseContent is always "-"
I am following the logback instruction here https://logback.qos.ch/manual/layouts.html#AccessPatternLayout
Am I missing some configuration?
Or is there some way to format the request log via code?
Thanks
