### ISSUE TITLE
dropziward-example doesn't write any file log

### ISSUE THREAD

**Issue by charbonnier666** [dropwizard/dropwizard#2068]
Hi all,
last versions of dropwizard (1.1.0 1.2.0) doesn't write any file log, neither in my application based on dropwizard-example neither in dropwizard-example without any modifications

**Comment by nickbabcock** [comment]
Correct, by default only logs get written to stdout, but you may add in file loggers.

**Comment by charbonnier666** [comment]
@nickbabcock in example.yml (and in my app) i have this:
not enough?

```
# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    com.example.app: DEBUG

    # Redirects SQL logs to a separate file
    org.hibernate.SQL:
      level: DEBUG

# Logback's Time Based Rolling Policy - archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}.log.gz
# Logback's Size and Time Based Rolling Policy -  archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
# Logback's Fixed Window Rolling Policy -  archivedLogFilenamePattern: /tmp/application-%i.log.gz

  appenders:
    - type: console
    **- type: file**
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      **currentLogFilename: /tmp/application.log**
      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB
```
