### ISSUE TITLE
AUDIT facility missing in io.dropwizard.logging.SyslogAppenderFactory.Facility enum

### ISSUE THREAD

**Issue by ashishs** [dropwizard/dropwizard#2173]
AUDIT facility missing in io.dropwizard.logging.SyslogAppenderFactory.Facility enum, even though logback supports it.
AUDIT facility is used for logging user access in many devices.

**Comment by isaki-x** [comment]
DropWizard has been making an effort of divorcing its hard dependency on logback and adding back a dependency seems like a step in the wrong direction. Does SLF4J support this?

**Comment by ashishs** [comment]
@isaki-x SLF4J supports the AUDIT facility.

**Comment by lightswitch05** [comment]
@ashishs you might be interested in my work-around. It isn't the most straightforward solution, but it works nicely and should be fairly resistant to future Dropwizard changes

First, create an AuditLogger class:

```java
/**
 * AuditLogger is a wrapper around a standard SLF4J logger specifically for AUDIT logs.
 * Since SLF4J does not allow for custom log levels, it works by adding a AUDIT marker
 * to all log messages. Log message are created under the ERROR level logs.
 *
 * @author Daniel White
 */
public final class AuditLogger {

    private static final Marker AUDIT_MARKER = MarkerFactory.getMarker("AUDIT");

    @SuppressWarnings("PMD:LoggerIsNotStaticFinal")
    private final Logger logger;

    private AuditLogger(final Class<?> clazz) {
        logger = LoggerFactory.getLogger(clazz);
    }

    public static AuditLogger getLogger(final Class<?> clazz) {
        return new AuditLogger(clazz);
    }

    /**
     * Create an AUDIT log with a string message.
     *
     * @param message the message string to be logged
     */
    public void log(final String message) {
        logger.error(AUDIT_MARKER, message);
    }

    /**
     * Log a AUDIT message according to the specified format and arguments.
     *
     * @param format    the format string
     * @param arguments a list of arguments
     */
    public void log(final String format, final Object... arguments) {
        logger.error(AUDIT_MARKER, format, arguments);
    }
}
```

Next, create two filter factories `AuditExcludeFilterFactory & `AuditOnlyFilterFactory`:

```java
/**
 * Creates a filter factory to only accept AUDIT logs. Use this filter
 * for appenders that should only contain AUDIT logs.
 */
@JsonTypeName("audit-exclude-filter-factory")
public class AuditExcludeFilterFactory implements FilterFactory<ILoggingEvent> {
    private static Filter<ILoggingEvent> auditFilter = new Filter<ILoggingEvent>() {
        @Override
        public FilterReply decide(final ILoggingEvent event) {
            Marker marker = event.getMarker();
            if (marker != null && "AUDIT".equals(marker.getName())) {
                return FilterReply.DENY;
            }
            return FilterReply.NEUTRAL;
        }
    };

    @Override
    public Filter<ILoggingEvent> build() {
        return auditFilter;
    }
}
```

```java
/**
 * Creates a filter factory to only accept AUDIT logs. Use this filter
 * for appenders that should only contain AUDIT logs.
 */
@JsonTypeName("audit-only-filter-factory")
public class AuditOnlyFilterFactory implements FilterFactory<ILoggingEvent> {
    private static Filter<ILoggingEvent> auditFilter = new Filter<ILoggingEvent>() {
        @Override
        public FilterReply decide(final ILoggingEvent event) {
            Marker marker = event.getMarker();
            if (marker != null && "AUDIT".equals(marker.getName())) {
                return FilterReply.ACCEPT;
            }
            return FilterReply.DENY;
        }
    };

    @Override
    public Filter<ILoggingEvent> build() {
        return auditFilter;
    }
}
```

Finally, configure your Dropwizard log appenders to use the Audit filters:

```yml
logging:
  loggers:
     level: ERROR

  appenders:
    - type: console
      filterFactories:
        - type: audit-exclude-filter-factory
    - type: console
      # This format is exactly the same as the default format, except that it uses the marker (AUDIT) instead of the log level (which is ERROR for audit logs)
      logFormat: "%-5marker [%d{ISO8601,UTC}] %c: %m%n%rEx"
      filterFactories:
        - type: audit-only-filter-factory
    - type: file
      currentLogFilename: logs/my-api.log
      archivedLogFilenamePattern: logs/my-api-%d-%i.log.gz
      maxFileSize: 100MB
      filterFactories:
        - type: audit-exclude-filter-factory
    - type: file
      currentLogFilename: logs/my-api-audit.log
      archivedLogFilenamePattern: logs/my-api-audit-%d-%i.log.gz
      maxFileSize: 100MB
      logFormat: "%-5marker [%d{ISO8601,UTC}] %c: %m%n%rEx"
      filterFactories:
        - type: audit-only-filter-factory
```

You also have to setup a `META-INF` entry for the log filters. See [Logging Filters](http://www.dropwizard.io/1.2.0/docs/manual/core.html#logging-filters)
