### ISSUE TITLE
ConsoleReporterFactory - not honoring expansions

### ISSUE THREAD

**Issue by roryodonnell** [dropwizard/dropwizard#2264]
It would be nice to have the ability to limit the metric expansions emitted to the console.

```
metrics:
    - type: console
      output: stdout
      excludes:
        - ch.
        - jvm.
      expansions:
        - COUNT
```
