### ISSUE TITLE
layout doesn't work with syslog appender

### ISSUE THREAD

**Issue by prathamesh13** [dropwizard/dropwizard#2371]
I am trying to use the `layout` option for the logging configuration to write json formatted logs to syslog using the `syslog` appender. The layout option works fine with `console` and `file` appender. I could see logs written in json format. But the same is not working for `syslog`. The logs written to syslog are not in json format. I don't get any exception parsing yaml configuration while starting the application that means `layout` can be specified for `syslog` appender. The documentation also doesn't mention any restriction on using `layout` with any particular type of appender. 

Below is my configuration:

configuration.yml:
```
  appenders:
    - type: console
      layout: 
        type: json
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/application.log
      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB
      layout:
        type: json
    - type: syslog
      host: localhost
      port: 514
      facility: local0
      threshold: ALL
      layout: 
        type: json
```
Am i missing something here. Is the `layout` option usable only with specific appenders? Is it possible to get syslog to use the `layout` option to write log messages in json format to syslog?

I have included the dependency for `dropwizard-json-logging` in my pom.

Does #2232 adds support for any specific appenders?
