### ISSUE TITLE
Multiple File Appenders Example is wrong

### ISSUE THREAD

**Issue by clrty** [dropwizard/dropwizard#2378]
The documentation is dropwizard 1.3.2 states the following:

> You can combine any number of different appenders, including multiple instances of the same appender with different configurations:

```yaml
logging:

  # Permit DEBUG, INFO, WARN and ERROR messages to be logged by appenders.
  level: DEBUG

  appenders:
    # Log warnings and errors to stderr
    - type: console
      threshold: WARN
      target: stderr

    # Log info, warnings and errors to our apps' main log.
    # Rolled over daily and retained for 5 days.
    - type: file
      threshold: INFO
      currentLogFilename: ./logs/example.log
      archivedLogFilenamePattern: ./logs/example-%d.log.gz
      archivedFileCount: 5

    # Log debug messages, info, warnings and errors to our apps' debug log.
    # Rolled over hourly and retained for 6 hours
    - type: file
      threshold: DEBUG
      currentLogFilename: ./logs/debug.log
      archivedLogFilenamePattern: ./logs/debug-%d{yyyy-MM-dd-hh}.log.gz
      archivedFileCount: 6
```

But the archivedLogFilenamePattern for the second file results in a logback error when starting the application:
> The date format in fileNamePattern will result in collisions in the names of archived log files.

The error show the following link for help: [Link](https://logback.qos.ch/codes.html#rfa_collision_in_dateFormat)
