### ISSUE TITLE
logformat not being honoured for type console-json

### ISSUE THREAD

**Issue by supreethrao** [dropwizard/dropwizard#2402]
When the appender type is console-json, the logFormat pattern is not being honoured. The configuration looks like this:

```
    - type: console-json
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
```

**Comment by nickbabcock** [comment]
`console-json` is not a valid type.

See the [dropwizard docs](https://www.dropwizard.io/1.3.4/docs/manual/core.html#json-log-format)

```yaml
logging:
  appenders:
    - type: console
      layout:
        type: json
```
