### ISSUE TITLE
Incomplete Jetty Request Log

### ISSUE THREAD

**Issue by aschilling** [dropwizard/dropwizard#2420]
HI everybody,

I would like to use the Jetty log to output all (Header and Form) request parameters. To do so I use the following configuration in the Dropwizard configuration file:

```
server:
  requestLog:
    appenders:
      - type: console
        threshold: DEBUG
        logFormat: "%t{yyyy-MM-dd HH:mm:ss.SSSZ} %a %m %fullRequest"
```

However, although I specified "%fullRequest" only a portion of the original request is logged, in particular all header parameters but no form parameters, are logged. If I use %requestContent nothing is printed out. Is it possible that if I use multi-part form data that this interferes with this setting? or are form-parameters in general not logged via %fullRequest setting?

I am using Dropwizard Version 1.1.8

Best regards
Andy
