### ISSUE TITLE
Could not resolve type id 'h2' - h2 parameter not recognised

### ISSUE THREAD

**Issue by ngton** [dropwizard/dropwizard#2425]
I'm getting the following exception when trying to use the h2 applicationConnector:

 * Failed to parse configuration at: server.applicationConnectors.[1]; Could not resolve type id 'h2' as a subtype of [simple type, class io.dropwizard.jetty.ConnectorFactory]: known type ids = [http, https] (for POJO property 'applicationConnectors')

This is my config: 

# server settings
server:
  rootPath: /1.0/top/
  applicationConnectors:
    - type: http
      port: 8080
    - type: h2
      port: 8445
      maxConcurrentStreams: 1024
      initialStreamRecvWindow: 65535
      keyStorePath: /space/tls/keyStore # required
      keyStorePassword: changeit
      trustStorePath: /space/tls/trustStore # required
      trustStorePassword: changeit
      supportedCipherSuites: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
  adminConnectors:
    - type: http
      port: 8081

**Comment by joschi** [comment]
@ngton Which version of Dropwizard are you using?
Which version of the JVM are you running the application with?
Have you added the necessary dependency on dropwizard-http2?
Have you configured Jetty ALPN (if necessary on your version of the JVM)?

**Comment by ngton** [comment]
@joschi Thank you!

I'm using DW 1.3.5

It was caused by missing dropwizard-http2. I'm now getting:

* Failed to parse configuration at: server.applicationConnectors.[1].supportedCipherSuites; Cannot deserialize instance of java.util.ArrayList out of VALUE_STRING token
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.ibm.itsm.topology.service.config.Config["server"]->io.dropwizard.server.DefaultServerFactory["applicationConnectors"]->java.util.ArrayList[1]->io.dropwizard.http2.Http2ConnectorFactory["supportedCipherSuites"])

Is that likely a JVM issue or another dependency that I'm missing?

**Comment by isaki-x** [comment]
It looks like supportedCipherSuites is supposed to be an array (based on the stack trace). See my change below.

```yml
server:
rootPath: /1.0/top/
applicationConnectors:
  - type: http
    port: 8080
  - type: h2
    port: 8445
    maxConcurrentStreams: 1024
    initialStreamRecvWindow: 65535
    keyStorePath: /space/tls/keyStore # required
    keyStorePassword: changeit
    trustStorePath: /space/tls/trustStore # required
    trustStorePassword: changeit
    supportedCipherSuites:
      - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
adminConnectors:
  - type: http
    port: 8081
```
