### ISSUE TITLE
Possible race condition causing invalid responses to requests (dropwizard 1.0+)

### ISSUE THREAD

**Issue by dpodder** [dropwizard/dropwizard#2457]
When we attempted to upgrade several of our projects from dropwizard 0.9.2 to 1.x, we ran into a bizarre, intermittent bug under high load that proved rather difficult to track down. The bug manifests as HTTP 400 responses to what should be valid requests; or, worse, certain requests receiving a the wrong response entirely (receiving the response for a different, earlier, request).

I have narrowed down the bug to a detectable race in `ByteBuffer` access within jetty ([link to the discussion here](http://dev.eclipse.org/mhonarc/lists/jetty-dev/msg03192.html)), but the root cause is still unknown. I *have* managed to reproduce it outside of our product's codebase, using a simple dropwizard server consisting of the getting started tutorial, with some minimal modifications. I'm working through the pipeline to getting the repro published, but in the meantime, I wanted to share what I can about the conditions needed to recreate this, in case anyone has seen it before (or runs into something similar).

The repro consists of a tiny dropwizard server, essentially the getting started tutorial, with two main API endpoints that are accessed at high load by a client. I'm not sure both are needed, but I haven't gotten around to trying anything simpler:

```
GET /category/{categoryName}
GET /category/{categoryName}/item/{itemName}
```

There's one notable change we did make to the standard configuration--enable logging globally at the `DEBUG` level, but drop anything below `INFO` at the appender level. We did encounter the bug without this custom logging config, but based on local testing, this makes the bug significantly easier to repro:

```
logging:
  level: DEBUG
  loggers:
    "io.dropwizard": INFO
  appenders:
    - type: console
      threshold: INFO
      target: stdout
      logFormat: '%d{ISO8601,UTC} %5p %mdc{debug-request-id:-na} %logger{40} - %m%n%rEx'
```

The bug repros across all of dropwizard 1.0, 1.1, 1.2, and even 1.3. It seems to repro as long as jetty 9.3 or 9.4 is used.
