### ISSUE TITLE
Disabling requestLog 

### ISSUE THREAD

**Issue by alexterman** [dropwizard/dropwizard#2598]
I would like to disable the requestLog writing.
The `appenders: []` is not working for me, coz I am using spring config server for holding configuration and it fails to parse this line right.

So I found 
```
  requestLog:
    type: external
``` 
option. But I wonder if this a right way?

**Comment by arteam** [comment]
I would say the `appenders: []` is a more idiomatic approach, but

```yaml
server:
  requestLog:
    type: external
    enabled: false
```

is effectively the same.
