### ISSUE TITLE
Dropwizard loses log under highly concurrent request traffic

### ISSUE THREAD

**Issue by Superluli** [dropwizard/dropwizard#2681]
During a performance test I found an issue that lots of logs are missing in our log file. I have a bare minimum dropwizard service to reproduce the issue that logs are lost under highly concurrent request traffic. The only maven dependency I have is `dropwizard-core 1.3.9`, and I have a test resource: 
```java
@Path("test")
@Produces(MediaType.APPLICATION_JSON)
public class TestResource {

    Logger LOGGER  = LoggerFactory.getLogger(TestResource.class);

    @GET
    public Response get() throws Exception{

    	MDC.put("version", "dropwizard default");

    	String id = UUID.randomUUID().toString();

    	LOGGER.info("start " + id);

    	Thread.sleep(new Random().nextInt(50));

    	LOGGER.info("end " + id);

        return Response.ok("{\"status\":\"ok\"}").build();
    }
}
```

and my app config is 
```yaml
server:
  applicationConnectors:
    - type: http
      port: 3080
  adminConnectors:
    - type: http
      port: 3081
  registerDefaultExceptionMappers: false

logging:
  level: INFO
  loggers:
    "root":
      additive: true
      appenders:
        - type: file
          logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} %level [%t] %logger{15} - context=[%mdc] message=%msg %n"
          currentLogFilename: '/tmp/test-app.log'
          archivedLogFilenamePattern: '/tmp/test-app-%d{yyyy-MM-dd}.log.gz'
          archivedFileCount: 1
  appenders:
    - type: console
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} %level [%t] %logger{15} - context=[%mdc] message=%msg %n"
```

I used 200 concurrent users to call the endpoint, 100 times, I'm supposed to get 120000 "start" and 20000 "end", but the result: 
![image](https://user-images.githubusercontent.com/2186223/53923976-fe432f80-402e-11e9-8503-b606b2c9a215.png)

After switching to external logback by adding a custom implementation of `io.dropwizard.logging.LoggingFactory` the issue is gone.
