### ISSUE TITLE
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'http' as a subtype of [simple type, class io.dropwizard.jetty.ConnectorFactory]: known type ids = [] (for POJO property 'applicationConnectors')

### ISSUE THREAD

**Issue by prakharrke** [dropwizard/dropwizard#3017]
Still getting this error in V1.3.8

I have configured shadowJar too.

I am deploying it on Heroku

Command used to run - web    java -Ddw.server.applicationConnectors[0].type="http" -Ddw.server.applicationConnectors[0].port="8080" -jar build/libs/ecommerce-1.0-SNAPSHOT.jar server ecommerce.yml

----------------------------------
yaml file - 
```yaml
template: ecommerce of, %s!
defaultName: Stranger
logging:
  level: INFO
  loggers:
    com.prakhar: DEBUG

server:
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091
  applicationContextPath: /*
  rootPath: /app/*

database :
  driverClass: org.postgresql.Driver
  user: ${DATABASE_USER}
  password: ${DATABASE_PSWD}
  url: ${DATABASE_URL}
  properties:
    charSet: UTF-8
    user: ecommerce
    password: password
    url: jdbc:postgresql://localhost:5432/ecommerce_dev
    # the maximum amount of time to wait on an empty pool before throwing an exception
    maxWaitForConnection: 1s

    # the SQL query to run when validating a connection's liveness
    validationQuery: "/* MyService Health Check */ SELECT 1"

    # the timeout before a connection validation queries fail
    validationQueryTimeout: 3s

    # the minimum number of connections to keep open
    minSize: 8

    # the maximum number of connections to keep open
    maxSize: 32

    # whether or not idle connections should be validated
    checkConnectionWhileIdle: false

    # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
    evictionInterval: 10s

    # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
    minIdleTime: 1 minute
```
