### ISSUE TITLE
Gzip not working

### ISSUE THREAD

**Issue by yazalulloa** [dropwizard/dropwizard#3280]
Hi, I'm trying to setup compression for my responses and I followed the documentation but does noting.

I created a small proyect to reproduce the error, and check if in my main project I had something that could interfere. I tested it with Postman and the request was always 1.3 MB, and that is the size of the file I'm using as a response (gzipTest.txt)

```
package org.test.gzip.test;

import io.dropwizard.Application;
import io.dropwizard.Configuration;
import io.dropwizard.setup.Bootstrap;
import io.dropwizard.setup.Environment;
import org.glassfish.jersey.logging.LoggingFeature;

import java.util.logging.Level;
import java.util.logging.Logger;

public class GzipTestApplication extends Application<Configuration> {

    public static void main(final String[] args) throws Exception {
        new GzipTestApplication().run(args);
    }

    @Override
    public void initialize(Bootstrap<Configuration> bootstrap) {
        super.initialize(bootstrap);
    }

    @Override
    public void run(Configuration configuration, Environment environment) throws Exception {

        LoggingFeature loggingFeature = new LoggingFeature(Logger.getLogger(LoggingFeature.DEFAULT_LOGGER_NAME), Level.INFO, LoggingFeature.Verbosity.PAYLOAD_ANY, LoggingFeature.DEFAULT_MAX_ENTITY_SIZE); //Level.ALL, LoggingFeature.Verbosity.PAYLOAD_ANY, LoggingFeature.DEFAULT_MAX_ENTITY_SIZE);
        environment.jersey().register(loggingFeature);
        environment.jersey().register(new GzipTestResource());
    }
}

```

```
package org.test.gzip.test;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.container.AsyncResponse;
import javax.ws.rs.container.Suspended;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

@Path("server")
public class GzipTestResource {

    @GET
    @Path("gzip_test")
    public void get(@Suspended AsyncResponse response) {
        
        try {
            String contents = new String(Files.readAllBytes(Paths.get("gzipTest.txt")));
            response.resume(contents);
        } catch (IOException e) {
            response.resume(e);
            e.printStackTrace();
        }

    }
}

```

```
server:
  type: simple
  connector:
    type: http
    port: 8080
  applicationContextPath: /v1
  gzip:
    enabled: true
    minimumEntitySize: 5 bytes
    bufferSize: 32KB
  requestLog:
    appenders:
      - type: console
        threshold: ALL
        timeZone: UTC
        target: stdout
        neverBlock: true

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      neverBlock: true
    - type: file
      currentLogFilename: ./log/application.log
      threshold: ALL
      timeZone: UTC
      archive: true
      archivedLogFilenamePattern: ./log/application-%d.log
      archivedFileCount: 20
      neverBlock: true

```

```

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.test</groupId>
    <artifactId>gzip-test</artifactId>
    <version>1.0.0</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <dropwizard.version>2.0.9</dropwizard.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.dropwizard</groupId>
                <artifactId>dropwizard-dependencies</artifactId>
                <version>${dropwizard.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-json-logging</artifactId>
        </dependency>

        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-core</artifactId>
        </dependency>

        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-forms</artifactId>
        </dependency>

        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-jackson</artifactId>
        </dependency>

        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-jersey</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.2.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

```
[gzipTest.txt](https://github.com/dropwizard/dropwizard/files/4582293/gzipTest.txt)
