### ISSUE TITLE
Dropwizard hibernate: using transactional and DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT in parallel requests generates the error "Cannot commit when autoCommit is enabled."

### ISSUE THREAD

**Issue by irineuruiz** [dropwizard/dropwizard#3291]
When we have `DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT` in our handling mode configuration and we try to use a resource with `transactional = true`,
if we make two parallel calls to this service we take the error "Cannot commit when `autoCommit` is enabled."

Can't use `DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT` and have a resource with `transactional = true`?
Or It's a bug?

Sample code:

```java
@Path("/test")
public class TestTransactionalWithAfterStatement {

	private PersonDAO dao;
	
	public TestTransactionalWithAfterStatement(PersonDAO dao) {
		this.dao = dao;
	}
	
	@Produces(MediaType.APPLICATION_JSON)
	@GET
    @Timed
    @UnitOfWork
    @Path("/{id}/name/{name}")
    public Long sayHello(@PathParam("id") int id, @PathParam("name") String name) throws InterruptedException {
		Person person = new Person(id, name);
		long number = dao.create(person);
		Thread.sleep(10000);
		return number;
    }
	
}
```

Hibernate config:

```
properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.jdbc.fetch_size: 1000
    hibernate.jdbc.batch_size: 30
    hibernate.connection.autocommit: false
    hibernate.connection.isolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
    hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate.connection.handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT
```

If we switch to `DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION` then it works...
