### ISSUE TITLE
Is there a way to show seonds value of timestamp instead of milliseconds in the json format log?

### ISSUE THREAD

**Issue by Lavie526** [dropwizard/dropwizard#3386]
I know dropwizard already support show json format log, i have a config.yml which support output json format log:
```yaml
logging:
  level: INFO
  loggers:
    oracle.bi.obis.nccsdropwizard: DEBUG
  appenders:
    - type: console
      layout:
        type: json
        prettyPrint: false
        appendLineSeparator: true
        includes: [timestamp, threadName, level, loggerName, message, mdc, exception]
        customFieldNames:
          timestamp: "time"
          message: "msg"
#        additionalFields:
#          service-name: "user-service"
        includesMdcKeys: [userId]
        flattenMdc: true
        exception:
          rootFirst: true
          depth: full
          evaluators: [org.apache]
```
The output of logs looks like this:
```
{"msg":"Registering jersey handler with root path prefix: /","time":1595580882221,"thread":"main","level":"INFO","logger":"io.dropwizard.server.DefaultServerFactory"}
```
Notice here is unit of the timestamp is milliseconds, i want to make it show the value with seconds, how should I config? Is there an easy way to do so?
