### ISSUE TITLE
Gzip compression not working in 2.0.12

### ISSUE THREAD

**Issue by vabs** [dropwizard/dropwizard#3406]
Hello,

I created a basic dropwizard application to test `gzip` compression for the responses.
But I don't have `content-encoding: gzip` header in my response for the application.

Config file:

```
logging:
  level: INFO
  loggers:
    com.invasa: DEBUG


server:
  gzip:
    enabled: true
    bufferSize: 8KB
```

Local Run:

<img width="849" alt="Test" src="https://user-images.githubusercontent.com/2936128/89913285-8bde6380-dbc1-11ea-9b9f-009dbadefb39.png">

Below is the application which I am using:

Sample Application: https://github.com/vabs/dropwizard-test
