### ISSUE TITLE
How to log logs with different log levels to different files in Dropwizard?

### ISSUE THREAD

**Issue by aditya-manit** [dropwizard/dropwizard#3450]
So Basically what I want to do is to log logs with different logs levels like INFO DEBUG WARN etc to different log files.

I have found something similar for slf4j [here](https://dzone.com/articles/log4j-tutorial-%E2%80%93-writing) but dropwizard uses logback as logging framework.

Can anybody tell me how to do it in dropwizard with logback? What changes should I make in my conifg.yml file?

```
 level: INFO
  loggers:
    "io.dropwizard": INFO
    "org.hibernate.SQL":
      level: DEBUG
      additive: false
      appenders:
        - type: file
          currentLogFilename: /var/log/myapplication-sql.log
          archivedLogFilenamePattern: /var/log/myapplication-sql-%d.log.gz
          archivedFileCount: 5
```
