### ISSUE TITLE
Dropwizard-migrations: Is there a way to pass property to changeset ?

### ISSUE THREAD

**Issue by swaroop4593** [dropwizard/dropwizard#4402]
I'm using below YAML file to store my configuration (as DataSourceFactory)
```
database:
  driverClass: com.mysql.jdbc.Driver
user: root
  password: ****
  url: jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
  properties:
    hibernate.jdbc.batch_size: 50
    hibernate.order_inserts: true
    hibernate.order_updates: true
    hibernate.jdbc.batch_versioned_data: true
```

Later on, I'm creating a migration bundle with the above configuration.

How can I pass a property (table_name) to a changeset from the configuration file to use something like this

```
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
				       http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-2.0.xsd">
    <changeSet author="test" id="test-1">
        <comment>test</comment>
        <sql>
            create or replace TABLE ${table_name} (
            KEY NUMBER(38, 0) NOT NULL autoincrement,
            PARAM_NAME VARCHAR(255),
            PARAM_VALUE VARCHAR(255),
            primary key (KEY)
            );
        </sql>
        <rollback>
            <dropTable tableName='${table_name}'/>
        </rollback>
    </changeSet>
</databaseChangeLog>
```
Note:  dropwizard version: 1.1.3

**Comment by zUniQueX** [comment]
The `dropwizard-migrations` package internally calls Liquibase. Therefore I would suggest looking into their docs. Maybe [this](https://docs.liquibase.com/concepts/basic/changelog-property-substitution.html) can help you.

If you want to pass properties dynamically from your Dropwizard application, I think there is currently no way for doing this. From Dropwizard 2.1.0 onwards (current master branch), there will be the possibility to pass objects/values to the Liquibase's `Scope` class, which then can be used in `CustomChange`s.

**Comment by swaroop4593** [comment]
I have a yaml file to set changelog properties
```
databaseChangeLog:
  property:
      name: table_name
      value: tableA
```

Is there a way to pass this yaml file as a parameter to dropwizard migrations?
