### ISSUE TITLE
Failed to parse configuration at: server.applicationConnectors; Could not resolve type id 'http' into a subtype of [simple type, class io.dropwizard.jetty.ConnectorFactory]

### ISSUE THREAD

**Issue by bretthoerner** [dropwizard/dropwizard#455]
Using the example config in 0.7-rc1 I receive the following

```
example.yml has an error:
  * Failed to parse configuration at: server.applicationConnectors; Could not resolve type id 'http' into a subtype of [simple type, class io.dropwizard.jetty.ConnectorFactory]
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.massrel.twitterproxy.ProxyConfig["server"]->io.dropwizard.server.DefaultServerFactory["applicationConnectors"])
```

Using this config:

```
server:
#  softNofileLimit: 1000
#  hardNofileLimit: 1000
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: example.keystore
      keyStorePassword: example
      validateCerts: false
# this requires the npn-boot library on the JVM's boot classpath
#    - type: spdy
#      port: 8445
#      keyStore: example.keystore
#      keyStorePassword: example
#      validateCerts: false
  adminConnectors:
    - type: http
      port: 8081
    - type: https
      port: 8444
      keyStorePath: example.keystore
      keyStorePassword: example
      validateCerts: false

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    com.example.app: DEBUG

    org.hibernate.SQL: ALL

  appenders:
    - type: console
```

I'm guessing it's a config or documentation issue, but I'm having no luck finding the root cause as I see the HTTP type declared here https://github.com/dropwizard/dropwizard/blob/master/dropwizard-jetty/src/main/java/io/dropwizard/jetty/HttpConnectorFactory.java#L164 but I'll admit to not being very fluent at Java. :)
