### ISSUE TITLE
Migration-doc for custom logger

### ISSUE THREAD

**Issue by dsvensson** [dropwizard/dropwizard#6936]
I have a custom logger similar to this https://github.com/dropwizard/dropwizard/issues/2419 and when upgrading from 2.1.5 to 4.0 sections like this cause config validation error:

```
  requestLog:
    type: logback-access-with-context
    appenders:
      - type: console
        layout:
          type: custom-access-json
```

Where `custom-access-json` comes from `@JsonTypeName` in my custom factory, and this name is what the exception refers to. I reverted back and unfortunately didn't save the exception. Maybe I'm just missing something, and if so, perhaps the upgrade notes documentation should mention this.
