### ISSUE TITLE
Configuration/Implementation of Logging to Multiple Files

### ISSUE THREAD

**Issue by DeanPoulin** [dropwizard/dropwizard#868]
I recently had a request from my DevOps group to have specific logs route to a separate log file so they could handle them differently than the standard dropwizard file logs. Think Personally Identifiable Information (PII) or Private Health Information (PHI) in logs.

I looked through some other discussions on this topic and it seemed like people were taking a few different approaches. Namely PR #567 via standard logback.xml which I'd like to avoid. My understanding is we'd like to enable this functionality without having to open up external configuration files.

I took a stab at implementing this via standard dropwizard yaml configuration to solve our issue as follows:

```yaml
level: INFO
loggers:
  com.example.app: DEBUG
console:
  enabled: true
  threshold: ALL
file:
  enabled: true
  threshold: ALL
  currentLogFilename: ./logs/example.log
  archivedLogFilenamePattern: ./logs/example-%d.log.gz
  archivedFileCount: 5
  appenders:
    - enabled: true
      threshold: INFO
      currentLogFilename: ./logs/activity.log
      archivedLogFilenamePattern: ./logs/activity-%d.log.gz
      logger: com.example.app.logging.LoggingFilter
      additive: false
    - enabled: true
      threshold: DEBUG
      currentLogFilename: ./logs/foo.log
      archivedLogFilenamePattern: ./logs/foo-%d.log.gz
      logger: com.example.app.logging.Foo
syslog:
  enabled: false
  host: localhost
  facility: local0
```

With the above configuration, logs for `com.example.app.logging.LoggingFilter` will be logged to an additional file `./logs/activity.log` and will *NOT* show up in the main log file for the service. Logs for `com.example.app.logging.Foo` will show up in the main log file and will also be logged to a separate file `./logs/foo.log`.

I'd love to get some feedback on this implementation: https://github.com/DeanPoulin/dropwizard/tree/0.6.2.x

I'd like to get this into 0.6.x since that's the version we're running in production. Hopefully this would also be trivial to get into 0.7.x and 0.8.x as well.
