### ISSUE TITLE
applicationContextPath doesn't work when SSL

### ISSUE THREAD

**Issue by edpichler** [dropwizard/dropwizard#940]
I'm using this configuration:
```
server:
  type: default
  rootPath: /v1
    applicationContextPath: /v1
    adminContextPath: /admin
```
This error is being throw:
```
server.yml has an error:
  * Unrecognized field at: server.applicationContextPath
    Did you mean?:
      - applicationConnectors
      - adminConnectors
      - adminMinThreads
      - allowedMethods
      - adminMaxThreads
        [15 more]
```
How do I configure the context path when SSL?

**Comment by carlo-rtr** [comment]
Please use issues for bugs or improvement. For getting help can you please use the google group dropwizard-user.

Your indentation looks off applicationContextPath should be under server. See https://github.com/dropwizard/dropwizard/blob/master/dropwizard-core/src/main/java/io/dropwizard/server/DefaultServerFactory.java#L101-L119

I think it should be like the below

```
server:
  type: default
  rootPath: /v1
  applicationContextPath: /v1
  adminContextPath: /admin
```
