### ISSUE TITLE
[Reissuing] How to set the applicationContextPath when using SSL on 0.7.1 version?

### ISSUE THREAD

**Issue by edpichler** [dropwizard/dropwizard#941]
I followed the documentation (http://dropwizard.io/manual/configuration.html) and it's not working.

Documentation said:
*"HTTPS: Extends the attributes that are available to the HTTP connector
Default: Extends the attributes that are available to all servers"*

I'm using this configuration:
```
server:
#  softNofileLimit: 1000
#  hardNofileLimit: 1000
  type: default
  applicationContextPath: /v1
  #adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: my.keystore
      keyStorePassword: 123456
      validateCerts: false
  adminConnectors:
    - type: http
      port: 8081
    - type: https
      port: 8444
      keyStorePath: my.keystore
      keyStorePassword: 123456
      validateCerts: false
```
This error is being throw:

```
server.yml has an error: 
* Unrecognized field at: server.applicationContextPath
    Did you mean?:
      - applicationConnectors
      - adminConnectors
      - adminMinThreads
      - allowedMethods
      - adminMaxThreads
        [15 more]
```
How do I configure the context path when SSL?
