### ISSUE TITLE
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "applicationConnectors"

### ISSUE THREAD

**Issue by Ghost-null66** [dropwizard/dropwizard#9736]
Error logs:
```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "applicationConnectors" (class io.dropwizard.core.server.SimpleServerFactory), not marked as ignorable (29 known properties: "registerDefaultExceptionMappers", "gid", "idleThreadTimeout", "applicationContextPath", "detailedJsonProcessingExceptionMapper", "user", "connector", "uid", "nofileHardLimit", "gzip", "maxQueuedRequests", "responseMeteredLevel", "umask", "metricPrefix", "shutdownGracePeriod", "maxThreads", "rootPath", "allowedMethods", "enableThreadNameFilter", "nofileSoftLimit", "dumpBeforeStop", "minThreads", "dumpAfterStart", "serverPush", "group", "enableVirtualThreads", "startsAsRoot", "requestLog", "adminContextPath"])
at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: com.dropwizard.dropwizardExampleConfiguration["server"]->io.dropwizard.core.server.SimpleServerFactory["applicationConnectors"])
```
With this config:
```
server:
  type: simple
  applicationConnectors:
    - type: http
      port: 9091
  adminConnectors:
    - type: http
      port: 9092
```
