### ISSUE TITLE
Logback's SizeAndTimeBasedRollingPolicy seems broken

### ISSUE THREAD

**Issue by pommepommee** [dropwizard/dropwizard#9868]
I am using dropwizard 4.0.1 on my application and I tried to apply a [SizeAndTimeBasedRollingPolicy](https://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy).

Unless I've misunderstood, it seems that file rotation doesn't work as expected. I've seen that it should be fixed according to #1173 by pull request #1660 and there is an [example](https://github.com/dropwizard/dropwizard/blob/f2431d2794d01d19b539dc7cf40f118dc15b0912/dropwizard-example/example.yml#L66) using this rolling policy so I don't understand why it is not working.

Here is my YAML configuration: 

```YAML
logging:
  appenders:
    - type: console
      threshold: INFO
    - type: file
      threshold: TRACE
      logFormat: "%d{yyyy/MM/dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %m %throwable{0}%n"
      currentLogFilename: ./../persistent/log/application-troubleshooting.log
      archivedLogFilenamePattern: ./../persistent/log/application-troubleshooting.%d{yyyy-MM-dd}-%i.log
      archivedFileCount: 3
      timeZone: UTC
      maxFileSize: 5MB
```

My understanding of this configuration is that dropwizard will create 3 files for each day (2025-02-18-1.log, 2025-02-18-2.log and 2025-02-18-3.log + the current log file) and will rotate the 3 files when the current log file reach the maxFileSize specified.

Thus, I have more than 3 archive files created: 
```
ls -alh
-rw-rw-r-- 1 thomas thomas  572 févr. 18 16:11 application.log
-rw-rw-r-- 1 thomas thomas  11M févr. 18 16:01 application-troubleshooting.2025-02-18-0.log
-rw-rw-r-- 1 thomas thomas 7,6M févr. 18 16:02 application-troubleshooting.2025-02-18-1.log
-rw-rw-r-- 1 thomas thomas 7,6M févr. 18 16:04 application-troubleshooting.2025-02-18-3.log
-rw-rw-r-- 1 thomas thomas 7,6M févr. 18 16:05 application-troubleshooting.2025-02-18-4.log
-rw-rw-r-- 1 thomas thomas 7,6M févr. 18 16:06 application-troubleshooting.2025-02-18-5.log
-rw-rw-r-- 1 thomas thomas 7,6M févr. 18 16:07 application-troubleshooting.2025-02-18-6.log
-rw-rw-r-- 1 thomas thomas 7,6M févr. 18 16:08 application-troubleshooting.2025-02-18-7.log
-rw-rw-r-- 1 thomas thomas 7,6M févr. 18 16:09 application-troubleshooting.2025-02-18-8.log
-rw-rw-r-- 1 thomas thomas 7,6M févr. 18 16:10 application-troubleshooting.2025-02-18-9.log
-rw-rw-r-- 1 thomas thomas 3,7M févr. 18 16:11 application-troubleshooting.log
```
